baseURL = '/'
languageCode = 'en-us'
title = 'Nitya Chidambaram'
theme = 'hugo-theme-stack'
DefaultContentLanguage = 'en'
hasCJKLanguage = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Stack theme configuration
  mainSections = ['posts']
  
  [params.sidebar]
    subtitle = 'Operator. Builder. Systems thinker.'
  
  [params.sidebar.avatar]
    enabled = true
    local = true
    src = 'img/profile-thumb.jpg'
  
  [params.footer]
    customText = 'Built with intent. Â© 2025 Nitya Chidambaram.'
  
[menu]
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 10
  
  [[menu.main]]
    identifier = "essays"
    name = "Essays"
    url = "/essays/"
    weight = 20
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
  
  [[menu.main]]
    identifier = "connect"
    name = "Connect"
    url = "/connect/"
    weight = 40
